services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_FIREBASE_API_KEY
        - VITE_FIREBASE_AUTH_DOMAIN
        - VITE_FIREBASE_PROJECT_ID
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - PORT=8080
      - BACKEND_URL=http://backend:3001
    env_file:
      - ./frontend/.env

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    env_file:
      - ./backend/.env
